import { useRouter } from "next/dist/client/router";
import Head from "next/head";
import { useState } from "react";
import Link from "next/link";
import SelectShared from "./components/Shared/SelectShared/SelectShared";
import SearchCariSekolah from "./components/SearchCariSekolah/SearchCariSekolah";

export default function Home({ nav, search }) {
  const router = useRouter();
  const [collapseOpen, setcollapseOpen] = useState(false);
  const [dropdownOpen, setdropdownOpen] = useState(false);
  const [activeMenu, setActiveMenu] = useState(`/`);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${!search ? "" : "bg-main pb-5 height-100vh"}`}>
        {!search ? (
          <div className="cari-sekolah">
            <div className="container">
              <div className="row justify-content-center">
                <div className="col-lg-3 col-md-5 col-sm-6 col-7 pt-5 p-4">
                  <img
                    src="/img/logo-smarteschool.png"
                    alt="logo"
                    className="img-fluid"
                  />
                </div>
              </div>
              <div className="row mb-5" style={{ marginTop: "75px" }}>
                <div className="col-md-12 text-center">
                  <h1 className="color-dark fw-black">
                    Cari <span className="color-primary">Sekolah</span>
                  </h1>
                  <h6 className="fw-bold mb-0">
                    Cari dan temukan sekolah untuk mendapatkan alamat tautan
                    menuju sekolah anda
                  </h6>
                </div>
              </div>
              <SearchCariSekolah nav={nav} />
            </div>
          </div>
        ) : (
          <>
            {" "}
            <section className="banner-cari-sekolah position-absolute"></section>
            <div className="container py-5 position-relative">
              <div className="row mb-5" style={{ zIndex: "1px" }}>
                <div className="col-md-12 text-center text-white pb-3">
                  <h1 className="fw-black">Cari Sekolah</h1>
                  <h6 className="fw-bold mb-0">
                    Cari dan temukan sekolah untuk mendapatkan alamat tautan
                    menuju sekolah anda
                  </h6>
                </div>
              </div>
              <div className="pt-4 mb-5 ">
                <SearchCariSekolah nav={nav} />
              </div>
              <div
                className="row pt-5 position-relative gy-4 search-rpp-content"
                style={{ zIndex: "50" }}
              >
                <div className="col-md-12 text-center mb-4">
                  <h2 className="color-dark fw-extrabold">SMK</h2>
                  <p className="fw-semibold">
                    1000 sekolah untuk kata kunci SMK
                  </p>
                </div>
              </div>
            </div>
          </>
        )}
      </main>

      {/* <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
        </a>
      </footer> */}
    </div>
  );
}

export async function getServerSideProps({ query: { nav, search } }) {
  return {
    props: {
      nav: nav || null,
      search: search || null,
    },
  };
}
